language: scala
dist: trusty
sudo: false
scala:
  - 2.12.4
jdk:
  - openjdk8

services:
  - docker
  - memcached
addons:
  postgresql: "9.5"

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

notifications:
  slack:
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}"
      - "Build %{commit}: %{commit_message}"
    rooms:
      secure: f10x2/Uu8gyami/QGXS4dVOehWAY9mAKWYchs6Wr92qgnCPW1ALpoZlRqQiVvjsjcByxjLuVz0NgUFT7RmPusV3OuVLpBetjb6J+55kWebhdAE7OlAhGgmhxLcdWFvBuql4hhN7GHfUNQv0wwabAHoiq/cbMC9uZYcJDdfznqAjSZvlb4t6zgGhNyCFJL0v1nTdJz64zo2SEUdwWFhaV7/k0wbpTjFytyySj0LVW5ymkApQD+Lqvn2KZBDMwtwrMH8derLLrqbj41UB7EsnGP4K7hh6HUOgf4aw2r46m/wFqTmwzgeD140iWslmDISprhSW2WAo5QG8hz0rKuywzHL/NB2WmRMF7Dg6tnG0zihVy+fJJ7CviVewC6DWUtHGZYENX6BNVImymAdVu2LIh+QrHUEjXlPRjBdH97ZEnSzc/RKIvVBRzyMZ5IAv4wZCuKHthPeTX17ZCp3mnL3BD/kXacabao0H0ot1fPaDBErmA5cp0STPh2OmPheKElLDoFHyXubeMPpicXTUkeFqnYTtrdLRgC+XvvHQegNkUO/rq/62BwC6ewSA7udHOj7w8fG9mSpOcEAsDbL7FOiqw64NVWMrTtWq0KaVyC+KESpaPgHWapbs9HCEFKdwtj+pygvilVDvqQDlp4KINYAhJynmATneh3T9Qa2Z2Juqrayw=

branches:
  only:
    - master
    - testing
    - dev

# Handle git submodules yourself
git:
    submodules: false

env:
  global:
    - RUMPEL_BUCKET=dswift-hat-sandbox-frontend-build-artifacts
    - AWS_DEFAULT_REGION=eu-west-1
    - secure: "MgysnY3V5IGKN2iU482TY8tTdkVZZHjcDSW991RvfUDs5MkWQh89FK77FSPxkA0Q8fbc6XLuv2zp8ULELZ6ff7RwEUUo8Kp6YQVazwMsNbmpBjLMuELZr9uwX4NxcS2S3gWrLnwvOdJ+1tzg+QNomDN7eB+8l599+obEVv9lteR7A0LE+lfhhGvahUr30SRfvlNFDXNJuyCLLPWRgaBL6YnTQ0marvIV75XoNRa6cC6SIFP8hwy4Q4aK9deNSlvhCmVDf/QQRhRgckMTTtGYfCneu7dq1cUtGiCBPEMhUO+gr4PCef72CtI2nGtb7NPweS91dxbxW85JIZrqvz6pk4R2N5kYARTxcRanh6b1bUTGO+D74GHQc/vXTRGzDfKbNjEyu1okJ1VFOhpoXrk1RdO5lQHOn+YFZMuzy/wYG7c7GwVO6Ht9sLu7mwDh2CdhKN1ksxz++LOfNXQu68ML6U8x8AJOzwBNDvhQ3kTdWhusF6EKoraUN3quqZS1pAEtsku7H7ZrxecEEura2s4EVUPh82ce5OayfHxiX0YO1W3K7whnUnJOZPiL0i0KzFIZc3BolEeSMb3z7hO3+xUcNxtp4bicp8ZCm41+11YNLwRrkT7CCE+LQDdwPv2HP+J8FfPnX/0No9hzAwwZrMdBgkEGxYErS0xSvxHq9leTGY4="
    - secure: "HhNX2ucfbCy3iJHuEjxPalxCIu1DEERLh9PZiD3SZ9A1B4JmDq5sSWMb8SQyXY8CtdgrLZlZbv389SCPm1HYV3Df8bJtzOwReYAoTM9wIUvMpViYGCvKj88dYKLC0cDzqAkFIA1oAjEe2R8Rck033hC6VUJs7GgOwfCdowD6tlCu6FzdOdT2nSjdrgcT+fXSMD0J06XuW8EFRW2tY+Ae9um/7s0lYvYUgfDRKOyfU12mcN34RJV+O1IPjoUFw7j3fxrFh1qyCC8bhCoi5ugccXIU+TRnQsZib4xaAZ0NItpb8A8nxskyMgYDN5jypE5mFeJdEeHj1bypqO3p5yAGBIEPPuPcCdsgfPnmQ+7eTjTdsGiFyPL8vX3E6Kfsi+UlX1VnNhd58qTE7Ootu55bc29W5vJEFH1xlYwrpdmn7ncDW9wgl6tjWxa603AM5LToNP2+vKsL0qXFf3TEoX10RbUn4tzbMkdR+d4RVLSuyXLO4aKWAi302nZvnrxBC+BH2iukNwmxpr2Z7TuyHVBzrilh4/yNpz7RhCdpl5kfMS1Q1pZne6ZtQ3XMuKyWj6/S7sESIhY/gk6OlZg5M5SoXTX0+SiSK4/RXP0CD1g+PqBPmJ5NCCRn4j/tpaoYqsOIQiF8Rb30VW10x5iS1XpM7W7Yp1BznoPuXwBJtQi6Nuk="
    - secure: USVpIy0emFH9ZvrkckuOxF3a9SsWOnH5a8XqZ/5WcA8xT+Jk3MDk8f1upx4DBpa4V4DRxI7Cvr326cP/Xi2gsBmgaKneo1tjACExIy42R9YZ8XPdr1Bbng7LDO4xfNSrKwMBUOeA1vF9/yZU4ki0Fv/J5wLYCthpnfEQ7+mubZ9h4dzFv0hd1wAinFR0vTVAn3+dQ4jaZSU9Tl/0L5T7y2Z2v/m9c4PHkII38WwdIvkrdY2jmSm0eSD7iEIwv3UwYk9BTIknmdHYfQ7xx256tRkadgMThmhdJhdm6JaLr819fXe30u/OIH15hLyM4ND+FjW6DvKNs3+2AVT7uOSK/wRntA2Fwvpczq7cwMxi2mU4HXXzH7a82Iswnm8Nn6Od+9vxsRV3nyl8XLmkn8Gn03k6+Pr2jj/ljdvGYeFmMYcvSlskE6VbWBGxyu6vAjccnUtGK9r3lkoxjX8CgiCev+/fwX5jlWvTSVeS8bvGy7dlRQQ2XRscQ8av5fKcACZOJVpQ4YgKnQ8j4MDUfT6sJ/8kONwXu4d6f9AREazZEml5taKvkZuDpHWPr77SqG+9Fccybm8IWjr0uq1eR+URsKJAXWj7ah0a7qA4M8WikH0FePR79YyyF2APm8KtDe7ZsbkbMdjVngrRhpACCUtsGLPhX4Y62szoBY8SzYJV/LI=
    - secure: garvO7sZMrDyhJ/LroK5SlidZCCBRa868Ebmuwwv75vlqeablbQk0LKEFqk6WjO428TIsu+JT0fkrg8eVoJPYO1n6/GhjtI9R4TgRNWcsoaFZe1RdCJkZoJemaeXkDomq34ZKRwnl7QsWeKInqtwDl3EJwoALaQjPPXEsrO20uodLKD8zFhCf89uQ4HIW6kAXJHTQSXByjkuRenhnyQ4nM/ixLnHZ+auJ/NG2RFUPADxRjpTNWcKoqvVh7QGzvYCiahDSaY669bZnLmTzOMH1EtVf8UPDFyHM56Pgq3a/OdOU4sxhSIdf3C+pbD8XV4lmU3gE/OLbybkk87YsU4J5iZLr552Dkm+g0ak2AnF4lxQwzm0sN/Q76eZRGpcBacncCLRlLK1kmWlfoJ6RrQTPRMBmNIzveCZ9gSY49AWEMUSn7ZG9F+MxCYnVAWlWDAEhKfQLYpHACa/GbGgvBaek6wG8vaeTMeBEVunpb3lsgQJ7fNBVtQ4vcn++0be1kW3+bAmPlviDJ+myey2O2uk1f5/T3k0s7UhbFcTzfN7HJ+2eIpg1Hp0FbmVEJvZVmE6TE8tiF0UwAJzbKDeU2HwGg8dXBbpKn/GWm70R1yytOCls4Mmndfxq75tnh9/ZRK7ihpa+TDg/xAjWqREGo1nHhObmY5L3rWxptyWKPgdVeA=

matrix:
  include:
    - env:
      - REPOSITORY_NAME=hubat
      - RUMPEL=sandbox
      - ALT_RUMPEL=sandbox-react
    - env:
      - REPOSITORY_NAME=hubofallthings
      - RUMPEL=live
      - ALT_RUMPEL=live-react
      - secure: "QrIhQCkVPMH6B+eKbdIRqpDyXyTS+SEJyQ3pz1GrrFipneQDZrwDj6VmYf00ebo1flNgEY/D/si1KoXk3NMfz3P9+3VzXzFOO4vjh2GShWJpvlSoo9FC31eSy2wCbtC7FVwOWn36200G2YL0UVVVG1vv+Sbto4Y8JUl/WahOoFix8R6v1ttyhnpVfknmTpxY/03btVdYkq03Yh9xqsMaAblATYvm1ApV/owy1FtfxY6Ykxwtd+aj0tnTAknJjAfk3irZXDQmLb6uGNPTH2YoijesdxpCq/YZhbUXEMQ+4YMGR9YU+3vR0gv65LGYk3+cdSn0teoDu6liiUxB80PKPEScyk68jfkfUvqDT0ODig02fKgVGi6QCQ2kcRFWEhZqlyHlO2UDndb4j632Zf+cwpPF4WZWoyN4BSgpeLM7VzpEYn4HF4MCLusya1feYe0Mn0gzLtTMaXu+K8c5OAqkyC3jKZBSFX98H2xNfpbrpV0op60QwY3Td7j7vd8q5b1/lub2xB3w/erfAs0wwVBfUbwVZrOFTMDt101t+hNAQBxqYHzP/6NhmfNizl/67erNQO+vMdeKqls6jKb0U/jvrkB4DiaIDuajUMHJKWh96SFKgeMjLQKKUlvNTBwJcULDeKio+vVdv1K3xLcS/MyzvoTPv7VjuAqYEv6JITtd0dk="
      - secure: "HuEUJ12CGLphVWHMHRK6IHOb2mGUqDlojzM6swozu6ceGAm2PlHUZm6SkdkvhAWq7sonjpnQKEC/42olocxSBi6SPOkHrWxIQMPTODr84XLI4gsyw9yh2eGENfYF0vyRTB4u8MbsJ0RvwEyyTzWNrmxeIsvVudYAsXGWfR1L/WA4J7luyGHeJ+ce96ZhKE5wJz67hPIzkOY2A/pkUdrrV8K+aObg+MZz9KdMl4g1S/nFNDIMwvB1VRzJ8kPkukcOkMN/t0uBXJT9YJZWfgTvHRhZJSkHkaMCAq3h0fYUeHDH1n4Dyir8VWuHW1NkEtF6yaLF6WA2Wa9Y1+Ucw4ANYrwgSy3Bu1kd06xwmbMTo/iVzL18I/2N7dj4s64mvsHkpf6YM1aBXoT+8GS4sjB/1NIAfGOi/dl5jjJKk5rkA9K89BmStUW737LbLADL0148aUrn5tNSsP2BoSKTjRSgqbBpsyH51ids7GqSOb0CKemibcAGaIGnzXza68cQgFnwAk6WIehukBeH7e+bGudhVDIuO+AIEVclHkOTDr3a8jxDqpEspqdSYAx+3J0K3zBbVqkkg2Ouj6AM4p9hA72SEWLulThZfGIP77Lv2VJvnrdCMUmZ5k8j/Zv6itd+9dR07vOH+Iq0Z/o6wIVBogyxBdMR6K+LInIeyp0aJAFNFqM=" 


# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

before_script:
  - psql -c "CREATE DATABASE testhatdb1;" -U postgres
  - psql -c "CREATE USER testhatdb1 WITH PASSWORD 'testing';" -U postgres
  - psql -c "GRANT CREATE ON DATABASE testhatdb1 TO testhatdb1" -U postgres
  - |
    if [[ "$TRAVIS_PULL_REQUEST" = "false" || -z "$RUMPEL" ]]; then
      cd ./hat/app/org/hatdex/hat/phata/assets/
      aws s3 cp s3://${RUMPEL_BUCKET}/${RUMPEL} rumpel --recursive
      aws s3 cp s3://${RUMPEL_BUCKET}/${ALT_RUMPEL} alt-rumpel --recursive
      cp rumpel/*.js* js/
      cp rumpel/*.css stylesheets/
      gzip --keep --force js/*.bundle.js
      cp -r rumpel/assets/* .
      cp -r alt-rumpel/* .
      rm -r rumpel
      rm -r alt-rumpel
      cd -
    fi

script:
  - sbt clean
  - sbt ++$TRAVIS_SCALA_VERSION compile
  - |
    if [[ "$REPOSITORY_NAME" = "hubat" ]]; then
      sbt ++$TRAVIS_SCALA_VERSION test:compile
      sbt ++$TRAVIS_SCALA_VERSION "project hat" coverage test -Dconfig.file=hat/conf/application.test.conf
    fi
  - sbt -Denv=prod docker:stage
  - docker build -t ${REPOSITORY_NAME}/hat:$(git rev-parse --short HEAD) hat/target/docker/stage

after_success:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
  - |
    if [[ "$TRAVIS_PULL_REQUEST" = "false" || -z "$RUMPEL" ]]; then
      sbt coverageReport && sbt coveralls
    fi

before_deploy:
  - unset AWS_SECRET_ACCESS_KEY;
    export AWS_SECRET_ACCESS_KEY=$DEPLOY_AWS_SECRET_ACCESS_KEY;
    unset AWS_ACCESS_KEY_ID;
    export AWS_ACCESS_KEY_ID=$DEPLOY_AWS_ACCESS_KEY_ID;
    ECR_REPOSITORY=$(aws ecr describe-repositories --repository-name ${REPOSITORY_NAME} --query 'repositories[0].repositoryUri' --output text);
    eval $(aws ecr get-login --no-include-email)
  - docker tag ${REPOSITORY_NAME}/hat:$(git rev-parse --short HEAD) ${ECR_REPOSITORY}:$(git rev-parse --short HEAD)

deploy:
  - provider: script
    script:
      - docker push ${ECR_REPOSITORY}:$(git rev-parse --short HEAD)
    skip_cleanup: true
    on:
      repo: Hub-of-all-Things/HAT2.0
      branch: dev
  - provider: script
    script:
      - docker push ${ECR_REPOSITORY}:$(git rev-parse --short HEAD)
    skip_cleanup: true
    on:
      repo: Hub-of-all-Things/HAT2.0
      branch: master
