apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hat.fullname" . }}  
  labels:
    {{- include "hat.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.env.config }}
  {{ $key }}: {{ $val }}
  {{- end }}
